import { TodoOptions } from "../types";
import { v4 as uuidv4 } from "uuid";

export const monthArr = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const todos: TodoOptions[] = [
  {
    id: uuidv4(),
    tittle: "Create Wireframe",
    startTime: "11:30 am",
    endTime: "12:00 pm",
    isCompleted: false,
    date: "Today",
  },
  {
    id: uuidv4(),
    tittle: "Create Wireframe",
    startTime: "11:30 am",
    endTime: "12:00 pm",
    isCompleted: false,
    date: "Today",
  },
  {
    id: uuidv4(),
    tittle: "Create Wireframe",
    startTime: "11:30 am",
    endTime: "12:00 pm",
    isCompleted: true,
    date: "Today",
  },
  {
    id: uuidv4(),
    tittle: "Create Wireframe",
    startTime: "11:30 am",
    endTime: "12:00 pm",
    isCompleted: false,
    date: "Today",
  },
  {
    id: uuidv4(),
    tittle: "Create Wireframe",
    startTime: "11:30 am",
    endTime: "12:00 pm",
    isCompleted: true,
    date: "Today",
  },
  {
    id: uuidv4(),
    tittle: "Create Wireframe",
    startTime: "11:30 am",
    endTime: "12:00 pm",
    isCompleted: false,
    date: "Today",
  },
  {
    id: uuidv4(),
    tittle: "Create Wireframe",
    startTime: "11:30 am",
    endTime: "12:00 pm",
    isCompleted: false,
    date: "Today",
  },
  {
    id: uuidv4(),
    tittle: "Create Wireframe",
    startTime: "11:30 am",
    endTime: "12:00 pm",
    isCompleted: false,
    date: "Today",
  },
  {
    id: uuidv4(),
    tittle: "Create Wireframe",
    startTime: "11:30 am",
    endTime: "12:00 pm",
    isCompleted: false,
    date: "Today",
  },
  {
    id: uuidv4(),
    tittle: "Create Wireframe",
    startTime: "11:30 am",
    endTime: "12:00 pm",
    isCompleted: false,
    date: "Today",
  },
  {
    id: uuidv4(),
    tittle: "Create Wireframe",
    startTime: "11:30 am",
    endTime: "12:00 pm",
    isCompleted: false,
    date: "Today",
  },
  {
    id: uuidv4(),
    tittle: "Create Wireframe",
    startTime: "11:30 am",
    endTime: "12:00 pm",
    isCompleted: false,
    date: "Today",
  },
  {
    id: uuidv4(),
    tittle: "Create Wireframe",
    startTime: "11:30 am",
    endTime: "12:00 pm",
    isCompleted: false,
    date: "Today",
  },
  {
    id: uuidv4(),
    tittle: "Create Wireframe",
    startTime: "11:30 am",
    endTime: "12:00 pm",
    isCompleted: false,
    date: "Today",
  },
  {
    id: uuidv4(),
    tittle: "Create Wireframe",
    startTime: "11:30 am",
    endTime: "12:00 pm",
    isCompleted: false,
    date: "Today",
  },
  {
    id: uuidv4(),
    tittle: "Create Wireframe",
    startTime: "11:30 am",
    endTime: "12:00 pm",
    isCompleted: false,
    date: "Today",
  },
];
